set(CMAKE_SYSTEM_NAME RAW)
set(CMAKE_SYSTEM_PROCESSOR msp430)
set(CMAKE_C_COMPILER_WORKS 1)

set(CMAKE_SYSROOT ${CMAKE_SOURCE_DIR}/../msp430-gcc)

set(MSP430_INSTALL_DIR ${CMAKE_SOURCE_DIR}/../msp430-gcc)
set(CMAKE_C_COMPILER ${MSP430_INSTALL_DIR}/bin/msp430-elf-gcc)
set(CMAKE_CXX_COMPILER ${MSP430_INSTALL_DIR}/bin/msp430-elf-c++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)